# This is the configuration used to check the rubocop source code.
# It was based in some configurations from: https://github.com/bbatsov/rubocop/tree/master/config

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - 'node_modules/**/*'
    - '**/node_modules/**/*'
    - 'spec/dummy/**/*'
    - 'db/migrate/**/*'
  TargetRubyVersion: 2.3

Metrics/LineLength:
  Max: 100

Style/Documentation:
  Exclude:
    - 'spec/dummy/**/*.rb'
    - '**/app/controllers/**/*.rb'

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*_spec.rb'

Style/UnneededPercentQ:
  Exclude:
    - 'spec/features/**/*_spec.rb'

Bundler/OrderedGems:
  Enabled: false
